[target.x86_64-unknown-linux-gnu]
rustflags = [
	"-Ctarget-cpu=native",
	# Faster linking & LTO things...
	"-Clink-arg=-fuse-ld=mold",
	"-Clink-arg=-flto",
	"-Clinker=clang++",
	"-Clinker-plugin-lto",
]
